export const initialSites = [
  {
    id: 1,
    subdomain: "",
    name: "しらんけど",
    description: "「いま日本で何が話題か」を客観ファクトと関西弁で自動分析するトレンドサイト。しらんけど。",
    genre: "general",
    logoUrl: "",
    isPublic: true,
    allowAutoPublish: true,
    youtubeThumbnailEnabled: true,
  },
];

export const initialCategories = [
  { id: 1, siteId: 1, slug: "all", name: "総合", sortOrder: 1 },
  { id: 2, siteId: 1, slug: "entertainment", name: "エンタメ", sortOrder: 2 },
  { id: 3, siteId: 1, slug: "game", name: "ゲーム", sortOrder: 3 },
  { id: 4, siteId: 1, slug: "tech", name: "IT・ガジェット", sortOrder: 4 },
  { id: 5, siteId: 1, slug: "social", name: "SNS・ネット話題", sortOrder: 5 },
  { id: 6, siteId: 1, slug: "gourmet", name: "グルメ・街ネタ", sortOrder: 6 },
  { id: 7, siteId: 1, slug: "life", name: "生活・雑学", sortOrder: 7 },
  { id: 8, siteId: 1, slug: "economy", name: "政治・経済", sortOrder: 8 },
];

export const initialTrendCandidates = [
  {
    id: 1,
    siteId: 1,
    normalizedKeyword: "千鳥大悟新作番組",
    displayKeyword: "千鳥 大悟 新作番組 ネット独占配信決定",
    sources: ["yahoo", "news", "youtube"],
    googleScore: 82,
    yahooScore: 94,
    youtubeScore: 85,
    newsScore: 88,
    gameScore: 10,
    shirankedoIndex: 88,
    isRapidRise: true,
    growthRate: 155.0,
    firstDetectedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    lastUpdatedAt: new Date().toISOString(),
    status: "completed",
  },
  {
    id: 2,
    siteId: 1,
    normalizedKeyword: "monsterhunterwildsアップデート",
    displayKeyword: "Monster Hunter Wilds 大型アプデ第1弾告知",
    sources: ["game", "youtube", "google"],
    googleScore: 92,
    yahooScore: 78,
    youtubeScore: 96,
    newsScore: 75,
    gameScore: 100,
    shirankedoIndex: 94,
    isRapidRise: true,
    growthRate: 210.0,
    firstDetectedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    lastUpdatedAt: new Date().toISOString(),
    status: "completed",
  },
  {
    id: 3,
    siteId: 1,
    normalizedKeyword: "道頓堀たこ焼き新展開",
    displayKeyword: "大阪 道頓堀 幻の老舗たこ焼き店 行列復活",
    sources: ["news", "yahoo", "google"],
    googleScore: 88,
    yahooScore: 82,
    youtubeScore: 70,
    newsScore: 85,
    gameScore: 0,
    shirankedoIndex: 86,
    isRapidRise: true,
    growthRate: 140.0,
    firstDetectedAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    lastUpdatedAt: new Date().toISOString(),
    status: "completed",
  },
  {
    id: 4,
    siteId: 1,
    normalizedKeyword: "新世代オープンソースaiモデル",
    displayKeyword: "新世代オープンソースAIモデルの日本語性能が話題に",
    sources: ["google", "news", "youtube"],
    googleScore: 75,
    yahooScore: 70,
    youtubeScore: 80,
    newsScore: 82,
    gameScore: 20,
    shirankedoIndex: 72,
    isRapidRise: false,
    growthRate: 35.0,
    firstDetectedAt: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
    lastUpdatedAt: new Date().toISOString(),
    status: "candidate",
  },
];

export const initialArticles = [
  {
    id: 1,
    siteId: 1,
    categoryId: 2,
    categoryName: "エンタメ",
    category: "エンタメ",
    title: "千鳥・大悟の新バラエティが独占配信へ 公式ティザーにSNS歓喜の声",
    slug: "trend-chidori-daigo-new-show",
    whyTrending: "大手動画配信サービスが千鳥・大悟の単独MCによるオリジナル新作を発表。公式PV公開と同時にXやYahoo!リアルタイム検索で1位に急上昇。",
    objectiveFact: "配信各社および公式リリースによると、即興コメディを主軸とした全10話構成で今秋から独占配信予定。豪華ゲストが毎週出演。",
    body: "大手動画配信サービスは14日、お笑いコンビ「千鳥」の大悟が単独で司会を務める完全新作バラエティ番組の制作および独占配信を発表しました。\n\n公式発表資料およびティザー映像によると、本作は台本一切なしの即興シチュエーションコメディを主軸とし、豪華ゲスト陣が多数出演する大型企画となっています。千鳥としてのレギュラー番組とはまた異なる大悟独自の世界観が展開されるとあり、お笑いファンを中心に期待の声が急速に広がっています。\n\n制作関係者向けの発表会では、地上波では実現しにくかった挑戦的な企画が盛り込まれることが明言されました。",
    content: "大手動画配信サービスは14日、お笑いコンビ「千鳥」の大悟が単独で司会を務める完全新作バラエティ番組の制作および独占配信を発表しました。\n\n公式発表資料およびティザー映像によると、本作は台本一切なしの即興シチュエーションコメディを主軸とし、豪華ゲスト陣が多数出演する大型企画となっています。千鳥としてのレギュラー番組とはまた異なる大悟独自の世界観が展開されるとあり、お笑いファンを中心に期待の声が急速に広がっています。\n\n制作関係者向けの発表会では、地上波では実現しにくかった挑戦的な企画が盛り込まれることが明言されました。",
    conclusionSentence: "今後の追加出演者や配信開始日の発表次第では、さらにネット上がざわつくことになりそうです。しらんけど。",
    shirankedoIndex: 88,
    indexLabel: "めっちゃ話題",
    isRapidRise: true,
    growthRate: 155.0,
    firstDetectedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1000&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1000&q=80",
    youtubeVideoId: "dQw4w9WgXcQ",
    status: "published",
    isDangerous: false,
    publishedAt: new Date(Date.now() - 1.5 * 3600 * 1000).toISOString(),
    pvCount: 4280,
    snsShareCount: 142,
    votes: { knew: 41, didntKnow: 72, grow: 85, end: 28 },
    commentsCount: 3,
  },
  {
    id: 2,
    siteId: 1,
    categoryId: 3,
    categoryName: "ゲーム",
    category: "ゲーム",
    title: "Monster Hunter Wilds 無料大型アプデ第1弾の詳細公開 新モンスター解禁",
    slug: "trend-mhw-wilds-update-1",
    whyTrending: "カプコン公式生放送で大型タイトルアップデート第1弾の配信日と追加モンスターが正式発表。SteamおよびSNSで爆発的な反響を記録。",
    objectiveFact: "歴戦の古龍種1体および過去作復活モンスター1体の実装が正式決定。武器バランス調整と新防具セットも同時追加。",
    body: "株式会社カプコンは、全世界で大ヒットを記録しているハンティングアクション最新作『Monster Hunter Wilds』の無料大型タイトルアップデート第1弾に関する公式ロードマップを公開しました。\n\n配信番組内の発表によると、新たな歴戦の古龍種モンスター1体と、過去作から復活を果たす人気モンスターが実装されます。また、武器バランスの調整や追加エンドコンテンツ、新防具シリーズの生産機能も同時解禁されることが確定しました。\n\n公式発表直後から国内外のゲームコミュニティやYouTubeライブ配信では装備ビルドの考察が白熱しています。",
    content: "株式会社カプコンは、全世界で大ヒットを記録しているハンティングアクション最新作『Monster Hunter Wilds』の無料大型タイトルアップデート第1弾に関する公式ロードマップを公開しました。\n\n配信番組内の発表によると、新たな歴戦の古龍種モンスター1体と、過去作から復活を果たす人気モンスターが実装されます。また、武器バランスの調整や追加エンドコンテンツ、新防具シリーズの生産機能も同時解禁されることが確定しました。\n\n公式発表直後から国内外のゲームコミュニティやYouTubeライブ配信では装備ビルドの考察が白熱しています。",
    conclusionSentence: "アップデート当日は狩猟解禁に合わせて有休を申請するハンターが続出する見通しです。しらんけど。",
    shirankedoIndex: 94,
    indexLabel: "めっちゃ話題",
    isRapidRise: true,
    growthRate: 210.0,
    firstDetectedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=1000&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=1000&q=80",
    youtubeVideoId: "M7lc1UVf-VE",
    status: "published",
    isDangerous: false,
    publishedAt: new Date(Date.now() - 3.5 * 3600 * 1000).toISOString(),
    pvCount: 5120,
    snsShareCount: 289,
    votes: { knew: 110, didntKnow: 35, grow: 124, end: 21 },
    commentsCount: 5,
  },
  {
    id: 3,
    siteId: 1,
    categoryId: 2,
    categoryName: "エンタメ",
    category: "エンタメ",
    title: "スタジオジブリ特別企画展 前売りチケットが開始3分で即完売の盛況",
    slug: "trend-ghibli-exhibition-tickets",
    whyTrending: "今夏開催されるスタジオジブリの回顧企画展の一般チケット販売が開始され、販売サイトへのアクセスが集中し即日完売。",
    objectiveFact: "主催者発表により、開幕初週末を含む先行販売枠が数分で上限到達。転売防止のための本人確認強化と追加日程の検討が公表された。",
    body: "都内美術館で開催予定のスタジオジブリ特別企画展の前売りチケット販売が本日午前10時に開始され、わずか数分で全日程の予定枚数が終了しました。\n\n本展覧会では、貴重な手描き背景画や未公開の設定資料、実物大の造形展示などが予定されており、国内のみならず海外ファンからも高い注目を集めていました。\n\n主催者側は公式サイトにて、転売チケットへの注意喚起を行うとともに、追加日程の調整について検討中である旨のアナウンスを行っています。",
    content: "都内美術館で開催予定のスタジオジブリ特別企画展の前売りチケット販売が本日午前10時に開始され、わずか数分で全日程の予定枚数が終了しました。\n\n本展覧会では、貴重な手描き背景画や未公開の設定資料、実物大の造形展示などが予定されており、国内のみならず海外ファンからも高い注目を集めていました。\n\n主催者側は公式サイトにて、転売チケットへの注意喚起を行うとともに、追加日程の調整について検討中である旨のアナウンスを行っています。",
    conclusionSentence: "プレミアム価格をつけた悪質な転売にはくれぐれもご注意ください。しらんけど。",
    shirankedoIndex: 78,
    indexLabel: "かなり話題",
    isRapidRise: false,
    growthRate: 45.0,
    firstDetectedAt: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1000&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1000&q=80",
    status: "published",
    isDangerous: false,
    publishedAt: new Date(Date.now() - 70 * 3600 * 1000).toISOString(),
    pvCount: 3410,
    snsShareCount: 88,
    votes: { knew: 55, didntKnow: 68, grow: 42, end: 81 },
    commentsCount: 2,
  },
  {
    id: 4,
    siteId: 1,
    categoryId: 4,
    categoryName: "IT・ガジェット",
    category: "IT・ガジェット",
    title: "新世代の日本語特化オープンソースAIが爆速進化 個人PCでも快適動作と話題",
    slug: "trend-japanese-llm-fast",
    whyTrending: "最新の軽量日本語LLMが公開され、軽量ながら高い関西弁認識率と推論速度を達成したことでエンジニア界隈でトレンド入り。",
    objectiveFact: "開発チームのベンチマークによると、メモリ8GBの一般的なノートPCでも秒間50トークン超の生成速度を記録。商用利用可能なライセンスで提供。",
    body: "国内外の研究機関および有志コミュニティによって開発された新世代の日本語特化オープンソース言語モデルが、エンジニアや生成AIファンの間で熱狂的な注目を集めています。\n\n従来の巨大モデルに匹敵する自然な日本語表現力を持ちながら、モデルの量子化により民生用パソコンのグラフィックボードやMacBookのオンボードメモリでも軽快に動作することが確認されました。\n\nさらに特筆すべき点として、関西弁や博多弁といった日本各地の方言のニュアンスを正確に汲み取った受け答えが可能になっており、今後の実用アプリケーションへの組み込みが期待されています。",
    content: "国内外の研究機関および有志コミュニティによって開発された新世代の日本語特化オープンソース言語モデルが、エンジニアや生成AIファンの間で熱狂的な注目を集めています。\n\n従来の巨大モデルに匹敵する自然な日本語表現力を持ちながら、モデルの量子化により民生用パソコンのグラフィックボードやMacBookのオンボードメモリでも軽快に動作することが確認されました。\n\nさらに特筆すべき点として、関西弁や博多弁といった日本各地の方言のニュアンスを正確に汲み取った受け答えが可能になっており、今後の実用アプリケーションへの組み込みが期待されています。",
    conclusionSentence: "AIが自然に関西弁でツッコミを入れてくる未来はもう目の前です。しらんけど。",
    shirankedoIndex: 82,
    indexLabel: "かなり話題",
    isRapidRise: true,
    growthRate: 110.0,
    firstDetectedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1000&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1000&q=80",
    status: "published",
    isDangerous: false,
    publishedAt: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
    pvCount: 3890,
    snsShareCount: 215,
    votes: { knew: 62, didntKnow: 45, grow: 98, end: 12 },
    commentsCount: 4,
  },
  {
    id: 5,
    siteId: 1,
    categoryId: 6,
    categoryName: "グルメ・街ネタ",
    category: "グルメ・街ネタ",
    title: "大阪・道頓堀の老舗たこ焼き店がまさかの新展開！？行列が絶えない真相",
    slug: "trend-dotonbori-takoyaki",
    whyTrending: "創業50年の有名たこ焼き店が新メニューと店舗リニューアルを発表し、地元民と外国人観光客の行列が朝から途切れない事態に。",
    objectiveFact: "秘伝の天然出汁を2倍に増量した『外カリ中トロ極み焼き』の提供を開始。各種グルメSNSで動画投稿が急増中。",
    body: "大阪ミナミの象徴とも言える道頓堀エリアにおいて、半世紀にわたり愛されてきた老舗たこ焼き店が打ち出した大胆なリニューアルが大きな話題を呼んでいます。\n\n新メニューでは、従来の生地に比べて出汁の旨味を大幅に凝縮し、焼き上がりの外側の香ばしさと中のトロトロ感のコントラストを極限まで高めたとのことです。試食した常連客からも『出汁の風味がガツンと来てビールが進む』と大絶賛の声が上がっています。\n\n週末には開店前から1時間以上の待ち時間が発生するなど、道頓堀の新たな名物スポットとして熱狂的な賑わいを見せています。",
    content: "大阪ミナミの象徴とも言える道頓堀エリアにおいて、半世紀にわたり愛されてきた老舗たこ焼き店が打ち出した大胆なリニューアルが大きな話題を呼んでいます。\n\n新メニューでは、従来の生地に比べて出汁の旨味を大幅に凝縮し、焼き上がりの外側の香ばしさと中のトロトロ感のコントラストを極限まで高めたとのことです。試食した常連客からも『出汁の風味がガツンと来てビールが進む』と大絶賛の声が上がっています。\n\n週末には開店前から1時間以上の待ち時間が発生するなど、道頓堀の新たな名物スポットとして熱狂的な賑わいを見せています。",
    conclusionSentence: "猫舌の人は火傷に十分気をつけてハフハフしながら食べてください。しらんけど。",
    shirankedoIndex: 86,
    indexLabel: "めっちゃ話題",
    isRapidRise: true,
    growthRate: 145.0,
    firstDetectedAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80",
    status: "published",
    isDangerous: false,
    publishedAt: new Date(Date.now() - 7 * 3600 * 1000).toISOString(),
    pvCount: 4620,
    snsShareCount: 167,
    votes: { knew: 78, didntKnow: 32, grow: 110, end: 15 },
    commentsCount: 6,
  },
  {
    id: 6,
    siteId: 1,
    categoryId: 5,
    categoryName: "SNS・ネット話題",
    category: "SNS・ネット話題",
    title: "「行けたら行くわ」の関西人、本当に行く確率は何％？驚きの街頭調査が拡散",
    slug: "trend-iketara-iku-kansai",
    whyTrending: "某深夜バラエティ番組とSNSアンケートが連動し、関西人の常套句「行けたら行く」の実際の出席率を徹底検証した動画が大バズり。",
    objectiveFact: "大阪・梅田および難波で実施された街頭アンケート200人調査によると、本当に行く確率は平均で『約3.8％』という結果に。",
    body: "関西圏で日常的に交わされる返答の定番『行けたら行くわ』について、実際に約束の場へ現れる確率を検証した調査結果がネット上で大反響を呼んでいます。\n\n調査結果によると、回答者の約9割が『ほぼ行かない時の丁寧なお断りフレーズとして使っている』と回答。『行けたら行くは行かないの同義語』であることが改めて客観的な数値として証明される形となりました。\n\n一方で『本当に予定が重なっていてギリギリまで行こうと努力したことはある』という擁護意見も散見され、SNS上では『関西の社交辞令文化』をめぐる大喜利大会へと発展しています。",
    content: "関西圏で日常的に交わされる返答の定番『行けたら行くわ』について、実際に約束の場へ現れる確率を検証した調査結果がネット上で大反響を呼んでいます。\n\n調査結果によると、回答者の約9割が『ほぼ行かない時の丁寧なお断りフレーズとして使っている』と回答。『行けたら行くは行かないの同義語』であることが改めて客観的な数値として証明される形となりました。\n\n一方で『本当に予定が重なっていてギリギリまで行こうと努力したことはある』という擁護意見も散見され、SNS上では『関西の社交辞令文化』をめぐる大喜利大会へと発展しています。",
    conclusionSentence: "もし『行けたら行く』と言われて本当に来たら、奇跡だと思って歓迎してあげてください。しらんけど。",
    shirankedoIndex: 92,
    indexLabel: "めっちゃ話題",
    isRapidRise: true,
    growthRate: 180.0,
    firstDetectedAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=1000&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=1000&q=80",
    status: "published",
    isDangerous: false,
    publishedAt: new Date(Date.now() - 4.5 * 3600 * 1000).toISOString(),
    pvCount: 6240,
    snsShareCount: 420,
    votes: { knew: 145, didntKnow: 18, grow: 160, end: 14 },
    commentsCount: 8,
  },
  {
    id: 7,
    siteId: 1,
    categoryId: 7,
    categoryName: "生活・雑学",
    category: "生活・雑学",
    title: "500円玉貯金を3年間コツコツ続けた結果、缶を開けたら予想外の金額に",
    slug: "trend-500yen-savings-3years",
    whyTrending: "30万円貯まる缶を3年かけて満杯にした投稿者が中身を集計した動画がYouTubeやXで合計300万再生を突破。",
    objectiveFact: "缶切りで開封した結果、合計で32万4,500円分が収納されていた。キャッシュレス化が進む中で小銭貯金の魅力が再注目。",
    body: "電子決済が主流となった現代において、あえてアナログな『500円玉貯金』を3年間完遂した一般投稿者の記録が多くのネットユーザーの関心を集めています。\n\n投稿者はお釣りで500円玉が出た時のみ専用の貯金缶に投入するルールを徹底。重さ数キロに達した缶を開封したところ、目標額の30万円を上回る32万円超がぎっしり詰まっていました。\n\n『日々の小さな積み重ねがこれほどのまとまった資産になるとは思わなかった』と語る投稿に対し、コメント欄では『明日から貯金箱買ってきます』『キャッシュレスで小銭が出ないから難易度上がった』など様々な反響が寄せられています。",
    content: "電子決済が主流となった現代において、あえてアナログな『500円玉貯金』を3年間完遂した一般投稿者の記録が多くのネットユーザーの関心を集めています。\n\n投稿者はお釣りで500円玉が出た時のみ専用の貯金缶に投入するルールを徹底。重さ数キロに達した缶を開封したところ、目標額の30万円を上回る32万円超がぎっしり詰まっていました。\n\n『日々の小さな積み重ねがこれほどのまとまった資産になるとは思わなかった』と語る投稿に対し、コメント欄では『明日から貯金箱買ってきます』『キャッシュレスで小銭が出ないから難易度上がった』など様々な反響が寄せられています。",
    conclusionSentence: "銀行に硬貨を持ち込むと大量両替手数料を取られることだけは覚悟しておいてください。しらんけど。",
    shirankedoIndex: 75,
    indexLabel: "かなり話題",
    isRapidRise: false,
    growthRate: 50.0,
    firstDetectedAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?auto=format&fit=crop&w=1000&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?auto=format&fit=crop&w=1000&q=80",
    status: "published",
    isDangerous: false,
    publishedAt: new Date(Date.now() - 45 * 3600 * 1000).toISOString(),
    pvCount: 2980,
    snsShareCount: 76,
    votes: { knew: 48, didntKnow: 52, grow: 65, end: 35 },
    commentsCount: 3,
  },
  {
    id: 8,
    siteId: 1,
    categoryId: 8,
    categoryName: "政治・経済",
    category: "政治・経済",
    title: "新紙幣発行から数ヶ月、街の自販機や券売機の対応状況をリアル徹底調査",
    slug: "trend-new-banknotes-vending",
    whyTrending: "新札が日常で流通し始めたものの、地方の飲食店や駐車場精算機で使えず困惑する声が依然としてネット上で話題に。",
    objectiveFact: "日本自動販売システム機械工業会の統計によると、飲料自販機の改修率は約6割、駐車場や個人飲食店の券売機は約5割にとどまる地域も。",
    body: "渋沢栄一、津田梅子、北里柴三郎の新紙幣が発行されて以降、街中での見かける頻度は急速に高まりましたが、自動精算機や自動販売機における受け入れ体制には依然として温度差が存在しています。\n\n大手コンビニや主要駅の自動券売機ではほぼ100％の対応が完了しているものの、個人経営のラーメン店やコインパーキング、病院の自動精算機などでは、高額な改修費用がネックとなり旧札のみ対応の機器がまだ少なくありません。\n\n店先に『新札は両替いたします』という手書きの案内が貼られる光景も日常茶飯事となっており、キャッシュレス決済への誘導がさらに加速する契機となっています。",
    content: "渋沢栄一、津田梅子、北里柴三郎の新紙幣が発行されて以降、街中での見かける頻度は急速に高まりましたが、自動精算機や自動販売機における受け入れ体制には依然として温度差が存在しています。\n\n大手コンビニや主要駅の自動券売機ではほぼ100％の対応が完了しているものの、個人経営のラーメン店やコインパーキング、病院の自動精算機などでは、高額な改修費用がネックとなり旧札のみ対応の機器がまだ少なくありません。\n\n店先に『新札は両替いたします』という手書きの案内が貼られる光景も日常茶飯事となっており、キャッシュレス決済への誘導がさらに加速する契機となっています。",
    conclusionSentence: "お財布には常に何枚か旧札か小銭を忍ばせておくのが一番安心なライフハックです。しらんけど。",
    shirankedoIndex: 79,
    indexLabel: "かなり話題",
    isRapidRise: false,
    growthRate: 65.0,
    firstDetectedAt: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1580519542036-c47de6196ba5?auto=format&fit=crop&w=1000&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1580519542036-c47de6196ba5?auto=format&fit=crop&w=1000&q=80",
    status: "published",
    isDangerous: false,
    publishedAt: new Date(Date.now() - 30 * 3600 * 1000).toISOString(),
    pvCount: 3750,
    snsShareCount: 92,
    votes: { knew: 82, didntKnow: 29, grow: 71, end: 40 },
    commentsCount: 4,
  },
  {
    id: 9,
    siteId: 1,
    categoryId: 3,
    categoryName: "ゲーム",
    category: "ゲーム",
    title: "Steam同接記録を更新したインディー和風ホラー、開発者は関西の1人クリエイター",
    slug: "trend-steam-indie-horror",
    whyTrending: "日本の古い屋敷を舞台にしたインディーホラーゲームが全世界の配信者の間で大流行し、Steamレビュー『圧倒的に好評』を獲得。",
    objectiveFact: "販売本数は初週で20万本を突破。個人開発者が夜間と週末のみを使って2年かけて制作したことがインタビューで判明。",
    body: "Steamのグローバル売上ランキングにおいて、名だたる大作ゲームを抑えて上位に食い込んだインディー和風ホラーゲーム『怪異の廻廊（仮）』が世界的な熱狂を巻き起こしています。\n\n緻密に作り込まれた昭和末期の日本家屋の不気味な静寂と、予測不能な怪異現象の演出が高く評価されており、TwitchやYouTubeでのゲーム実況プレイ配信が爆発的に急増しました。\n\n開発者が関西在住の会社員によるワンマンプロジェクトであることが明かされると、ゲーム開発者コミュニティやファンの間では賞賛と驚きの声が相次いでいます。",
    content: "Steamのグローバル売上ランキングにおいて、名だたる大作ゲームを抑えて上位に食い込んだインディー和風ホラーゲーム『怪異の廻廊（仮）』が世界的な熱狂を巻き起こしています。\n\n緻密に作り込まれた昭和末期の日本家屋の不気味な静寂と、予測不能な怪異現象の演出が高く評価されており、TwitchやYouTubeでのゲーム実況プレイ配信が爆発的に急増しました。\n\n開発者が関西在住の会社員によるワンマンプロジェクトであることが明かされると、ゲーム開発者コミュニティやファンの間では賞賛と驚きの声が相次いでいます。",
    conclusionSentence: "部屋を真っ暗にしてヘッドホンでプレイすると夢に出てくるので注意してください。しらんけど。",
    shirankedoIndex: 89,
    indexLabel: "めっちゃ話題",
    isRapidRise: true,
    growthRate: 175.0,
    firstDetectedAt: new Date(Date.now() - 15 * 3600 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1000&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1000&q=80",
    status: "published",
    isDangerous: false,
    publishedAt: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    pvCount: 4890,
    snsShareCount: 310,
    votes: { knew: 67, didntKnow: 43, grow: 115, end: 18 },
    commentsCount: 5,
  },
  {
    id: 10,
    siteId: 1,
    categoryId: 4,
    categoryName: "IT・ガジェット",
    category: "IT・ガジェット",
    title: "最新スマホのカメラが一眼レフ並みに進化、ただし本体重量も文鎮級らしいで",
    slug: "trend-flagship-smartphone-heavy",
    whyTrending: "各社フラッグシップスマホの大型1インチセンサー搭載が加速する一方、手首への負担を訴えるレビューがSNSで共感を呼ぶ。",
    objectiveFact: "主要メーカーの最上位モデル重量はいずれも220g〜240gを超過。画質向上とトレードオフの重量増加が実機テストで検証された。",
    body: "スマートフォンのカメラ性能競争が極限に達し、暗所撮影や望遠ズーム性能が本格的なミラーレス一眼レフに肉薄するレベルへと進化を遂げています。\n\nしかし、大型センサーや潜望鏡型ペリスコープ望遠レンズ、放熱用ベイパーチャンバーの搭載に伴い、最新のハイエンド端末の本体重量は230gをゆうに超えるケースが常態化してきました。\n\nスマートフォンアクセサリ市場では、小指の変形や腱鞘炎を予防するためのスマホリングや軽量ケースが飛ぶように売れており、高画質と携帯性の両立をめぐるユーザーの葛藤が続いています。",
    content: "スマートフォンのカメラ性能競争が極限に達し、暗所撮影や望遠ズーム性能が本格的なミラーレス一眼レフに肉薄するレベルへと進化を遂げています。\n\nしかし、大型センサーや潜望鏡型ペリスコープ望遠レンズ、放熱用ベイパーチャンバーの搭載に伴い、最新のハイエンド端末の本体重量は230gをゆうに超えるケースが常態化してきました。\n\nスマートフォンアクセサリ市場では、小指の変形や腱鞘炎を予防するためのスマホリングや軽量ケースが飛ぶように売れており、高画質と携帯性の両立をめぐるユーザーの葛藤が続いています。",
    conclusionSentence: "寝転びながら顔の上に落とすと鼻骨が折れそうになるので十分気をつけてください。しらんけど。",
    shirankedoIndex: 76,
    indexLabel: "かなり話題",
    isRapidRise: false,
    growthRate: 40.0,
    firstDetectedAt: new Date(Date.now() - 28 * 3600 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?auto=format&fit=crop&w=1000&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?auto=format&fit=crop&w=1000&q=80",
    status: "published",
    isDangerous: false,
    publishedAt: new Date(Date.now() - 25 * 3600 * 1000).toISOString(),
    pvCount: 3120,
    snsShareCount: 84,
    votes: { knew: 58, didntKnow: 39, grow: 60, end: 45 },
    commentsCount: 3,
  },
  {
    id: 11,
    siteId: 1,
    categoryId: 6,
    categoryName: "グルメ・街ネタ",
    category: "グルメ・街ネタ",
    title: "関西限定の「超濃厚抹茶パフェ」がSNSで大バズり 開店前から100人超の行列",
    slug: "trend-kansai-matcha-parfait",
    whyTrending: "京都の老舗茶舗がプロデュースした究極の濃茶パフェがTikTokやInstagramで拡散され、整理券が朝8時で配布終了する事態に。",
    objectiveFact: "宇治産の一番茶のみを使用した特製抹茶ジェラートとマスカルポーネクリームを7層に重ねた限定スイーツ。1日限定150食。",
    body: "京都・宇治の伝統ある茶農家が直営する甘味カフェがリリースした新作『極濃・宇治抹茶ティラミスパフェ』が、SNS世代のスイーツファンの心を鷲掴みにしています。\n\nスプーンを入れた瞬間に立ち上る芳醇なお茶の香りと、甘さを極力控えた本格的な苦味・旨味のバランスが唯一無二と評され、連日他府県からも多くの観光客が詰めかけています。\n\n『今まで食べていた抹茶スイーツは何だったのか』と衝撃を受けるインフルエンサーのショート動画が相次ぎ、週末の待ち時間は最長2時間半を記録する異例の人気となっています。",
    content: "京都・宇治の伝統ある茶農家が直営する甘味カフェがリリースした新作『極濃・宇治抹茶ティラミスパフェ』が、SNS世代のスイーツファンの心を鷲掴みにしています。\n\nスプーンを入れた瞬間に立ち上る芳醇なお茶の香りと、甘さを極力控えた本格的な苦味・旨味のバランスが唯一無二と評され、連日他府県からも多くの観光客が詰めかけています。\n\n『今まで食べていた抹茶スイーツは何だったのか』と衝撃を受けるインフルエンサーのショート動画が相次ぎ、週末の待ち時間は最長2時間半を記録する異例の人気となっています。",
    conclusionSentence: "お抹茶のカフェイン効果で夜なかなか眠れなくなる可能性があるので夕方以降の食べ過ぎには注意です。しらんけど。",
    shirankedoIndex: 84,
    indexLabel: "かなり話題",
    isRapidRise: true,
    growthRate: 135.0,
    firstDetectedAt: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1000&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1000&q=80",
    status: "published",
    isDangerous: false,
    publishedAt: new Date(Date.now() - 9 * 3600 * 1000).toISOString(),
    pvCount: 3950,
    snsShareCount: 153,
    votes: { knew: 43, didntKnow: 61, grow: 88, end: 20 },
    commentsCount: 4,
  },
  {
    id: 12,
    siteId: 1,
    categoryId: 7,
    categoryName: "生活・雑学",
    category: "生活・雑学",
    title: "朝イチの白湯（さゆ）健康法は本当に効くのか？医学的根拠とファンの声",
    slug: "trend-morning-warm-water",
    whyTrending: "有名女優やタレントが相次いでモーニングルーティンとして紹介し、検索ボリュームが前年同期比で180％増加。",
    objectiveFact: "内科医や管理栄養士の解説によると、胃腸の蠕動運動促進や基礎体温の上昇、血流改善に一定の生理学的効果が認められている。",
    body: "沸騰させたお湯を50度前後に冷まして毎朝コップ一杯飲む『白湯健康法』が、手軽でお金のかからない健康習慣として世代を問わず定着を見せています。\n\n医学的観点からも、起床直後の冷えた内臓を優しく温めることで副交感神経から交感神経へのスムーズな切り替えが促され、便秘解消や代謝アップに寄与することが裏付けられています。\n\n『ただのお湯なのに体がポカポカして肌の調子が良くなった』という実感の声が多い一方で、『急激に熱いお湯を飲むと食道に負担がかかるため適温を守ることが肝要』との専門家のアドバイスも共有されています。",
    content: "沸騰させたお湯を50度前後に冷まして毎朝コップ一杯飲む『白湯健康法』が、手軽でお金のかからない健康習慣として世代を問わず定着を見せています。\n\n医学的観点からも、起床直後の冷えた内臓を優しく温めることで副交感神経から交感神経へのスムーズな切り替えが促され、便秘解消や代謝アップに寄与することが裏付けられています。\n\n『ただのお湯なのに体がポカポカして肌の調子が良くなった』という実感の声が多い一方で、『急激に熱いお湯を飲むと食道に負担がかかるため適温を守ることが肝要』との専門家のアドバイスも共有されています。",
    conclusionSentence: "猫舌の人が無理して飲むと朝から大惨事になるのでしっかりフーフー冷ましてください。しらんけど。",
    shirankedoIndex: 71,
    indexLabel: "話題",
    isRapidRise: false,
    growthRate: 30.0,
    firstDetectedAt: new Date(Date.now() - 50 * 3600 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=80",
    status: "published",
    isDangerous: false,
    publishedAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    pvCount: 2450,
    snsShareCount: 45,
    votes: { knew: 75, didntKnow: 25, grow: 50, end: 50 },
    commentsCount: 2,
  },
  {
    id: 13,
    siteId: 1,
    categoryId: 5,
    categoryName: "SNS・ネット話題",
    category: "SNS・ネット話題",
    title: "「知らんけど」が若者言葉アワード上位にランクイン 汎用性の高さに全国が脱帽",
    slug: "trend-shirankedo-national-trend",
    whyTrending: "SNSや日常会話で使われるパワーワード調査において「知らんけど」が関西圏を飛び越えて全国のZ世代・ビジネス層にまで浸透。",
    objectiveFact: "流行語アワードやSNS言及数分析において上位入賞。文末につけるだけで場の緊張を和らげ免責できる魔法の言葉として定着。",
    body: "元々は関西弁特有の言い回しであった『知らんけど』が、いまや全国区のコミュニケーションツールとして驚異的な広がりを見せています。\n\n真面目な意見や熱弁を振るった直後に『…知らんけど。』と付け加えることで、自分の主張を押し付けず、会話の場を和ませるクッション言葉としての機能が現代の若者カルチャーと絶妙にマッチしました。\n\n『責任を回避しつつ本音を言える最強の構文』としてビジネスチャットの雑談チャンネルでも活用されるなど、言葉の持つ独特の脱力感が愛され続けています。",
    content: "元々は関西弁特有の言い回しであった『知らんけど』が、いまや全国区のコミュニケーションツールとして驚異的な広がりを見せています。\n\n真面目な意見や熱弁を振るった直後に『…知らんけど。』と付け加えることで、自分の主張を押し付けず、会話の場を和ませるクッション言葉としての機能が現代の若者カルチャーと絶妙にマッチしました。\n\n『責任を回避しつつ本音を言える最強の構文』としてビジネスチャットの雑談チャンネルでも活用されるなど、言葉の持つ独特の脱力感が愛され続けています。",
    conclusionSentence: "このサイトの名前もまさにそこから取られているわけですが、本当に役に立つかどうかは…知らんけど。",
    shirankedoIndex: 96,
    indexLabel: "めっちゃ話題",
    isRapidRise: true,
    growthRate: 250.0,
    firstDetectedAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1516251193007-45ef944ab0c6?auto=format&fit=crop&w=1000&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1516251193007-45ef944ab0c6?auto=format&fit=crop&w=1000&q=80",
    status: "published",
    isDangerous: false,
    publishedAt: new Date(Date.now() - 2.5 * 3600 * 1000).toISOString(),
    pvCount: 7850,
    snsShareCount: 512,
    votes: { knew: 160, didntKnow: 10, grow: 180, end: 12 },
    commentsCount: 9,
  },
  {
    id: 14,
    siteId: 1,
    categoryId: 8,
    categoryName: "政治・経済",
    category: "政治・経済",
    title: "関西万博の新パビリオン完成イメージが公開 未来都市体験に期待高まる",
    slug: "trend-expo-pavilion-future",
    whyTrending: "2025年大阪・関西万博の目玉となるシグネチャーパビリオンの最新CGレンダリングおよび体験コンテンツが公式アナウンス。",
    objectiveFact: "空飛ぶクルマの運航デモや最先端医療・バイオテクノロジーの展示概要が発表。国内外の観光客予約受付も順次拡大中。",
    body: "2025年に大阪・夢洲で開催される日本国際博覧会（大阪・関西万博）において、来場者の注目を集めるパビリオン群の完成予想図が新たに公開されました。\n\n大屋根リングの建設が進む中、最新のデジタル技術と自然環境が融合した独創的な建築デザインや、次世代モビリティ『空飛ぶクルマ』の離着陸ポートの詳細が明らかになり、関係者やファンの期待が膨らんでいます。\n\n会場内では最先端の生成AIを活用した多言語アテンドや没入型メタバース体験も導入される見通しとなっており、関西発のグローバルイベントとしてカウントダウンが加速しています。",
    content: "2025年に大阪・夢洲で開催される日本国際博覧会（大阪・関西万博）において、来場者の注目を集めるパビリオン群の完成予想図が新たに公開されました。\n\n大屋根リングの建設が進む中、最新のデジタル技術と自然環境が融合した独創的な建築デザインや、次世代モビリティ『空飛ぶクルマ』の離着陸ポートの詳細が明らかになり、関係者やファンの期待が膨らんでいます。\n\n会場内では最先端の生成AIを活用した多言語アテンドや没入型メタバース体験も導入される見通しとなっており、関西発のグローバルイベントとしてカウントダウンが加速しています。",
    conclusionSentence: "会場の広さは半端ないので、歩きやすい靴で行くことだけは強くおすすめしておきます。しらんけど。",
    shirankedoIndex: 85,
    indexLabel: "めっちゃ話題",
    isRapidRise: true,
    growthRate: 130.0,
    firstDetectedAt: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1000&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1000&q=80",
    status: "published",
    isDangerous: false,
    publishedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    pvCount: 4120,
    snsShareCount: 178,
    votes: { knew: 70, didntKnow: 45, grow: 92, end: 28 },
    commentsCount: 4,
  },
  {
    id: 15,
    siteId: 1,
    categoryId: 5,
    categoryName: "SNS・ネット話題",
    category: "SNS・ネット話題",
    title: "【保留記事】事件の某容疑者に関するSNS上の個人特定デマ騒動",
    slug: "trend-held-rumor-case",
    whyTrending: "SNS上で無関係の一般人の氏名や勤務先が容疑者として拡散。危険ジャンル検知により安全ブレーキが自動作動し保留。",
    objectiveFact: "警察発表および大手報道機関による公式裏付けは一切確認されておらず、明らかなデマである可能性が極めて高い。",
    body: "ネット上の匿名掲示板およびSNSにおいて、事件の容疑者であるかのように装った一般人の個人情報が拡散されています。警察発表および大手報道機関による公式裏付けは一切確認されておらず、明らかなデマである可能性が極めて高いため、当サイトでは安全ブレーキが作動しました。",
    content: "ネット上の匿名掲示板およびSNSにおいて、事件の容疑者であるかのように装った一般人の個人情報が拡散されています。警察発表および大手報道機関による公式裏付けは一切確認されておらず、明らかなデマである可能性が極めて高いため、当サイトでは安全ブレーキが作動しました。",
    conclusionSentence: "未確認の噂を軽はずみに拡散すると法的責任を問われる可能性があります。しらんけど。",
    shirankedoIndex: 52,
    indexLabel: "話題",
    isRapidRise: true,
    growthRate: 130.0,
    firstDetectedAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=1000&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=1000&q=80",
    status: "on_hold",
    isDangerous: true,
    dangerReason: "危険キーワード検知: 容疑, 特定 / 一次ソース不足 (SNS噂のみ)",
    publishedAt: new Date().toISOString(),
    pvCount: 120,
    snsShareCount: 0,
    votes: { knew: 12, didntKnow: 9, grow: 5, end: 16 },
    commentsCount: 0,
  },
];
